# Generated by Django 4.2.16 on 2024-10-19 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0002_budget_category_emi_expense_income_input_save_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Userprofile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("profession", models.CharField(blank=True, max_length=100)),
                ("savings", models.IntegerField(blank=True, null=True)),
                ("income", models.BigIntegerField(blank=True, null=True)),
                ("pro_pic", models.ImageField(blank=True, upload_to="pro_image")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
