# Generated by Django 4.2.16 on 2024-11-11 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budget",
            name="period",
        ),
        migrations.AddField(
            model_name="budget",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="budget",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="budget",
            name="total_budget",
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=10),
            preserve_default=False,
        ),
    ]
