# Generated by Django 4.2.16 on 2024-11-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_remove_budget_period_budget_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="pro_pic",
            field=models.ImageField(
                blank=True, default="default.jpg", upload_to="pro_image"
            ),
        ),
    ]
