# Generated by Django 4.2.16 on 2024-11-13 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_userprofile_pro_pic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="email",
        ),
    ]
